# Generated by Django 3.0.9 on 2020-08-17 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=150)),
                ('imagen', models.URLField(default='https://m.media-amazon.com/images/G/01/imdb/images/nopicture/medium/name-2135195744._CB466677935_.png', help_text='De imdb mismo')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actores', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Actores')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('estreno', models.IntegerField(default=2000)),
                ('imagen', models.URLField(help_text='De imdb mismo')),
                ('resumen', models.TextField(help_text='Descripción corta')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('estreno', models.IntegerField(default=2000)),
                ('temporadas', models.IntegerField(default=1)),
                ('episodios', models.IntegerField(default=1)),
                ('imagen', models.URLField(help_text='De imdb mismo')),
                ('resumen', models.TextField(help_text='Descripción corta')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='PeliculaFavorita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=150)),
                ('imagen', models.URLField(default='https://m.media-amazon.com/images/G/01/imdb/images/nopicture/medium/name-2135195744._CB466677935_.png', help_text='De imdb mismo')),
                ('peliculas', models.ManyToManyField(null=True, through='api.Casting', to='api.Pelicula')),
                ('series', models.ManyToManyField(null=True, through='api.Casting', to='api.Series')),
            ],
        ),
        migrations.AddField(
            model_name='casting',
            name='directores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Directores'),
        ),
        migrations.AddField(
            model_name='casting',
            name='pelicula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Pelicula'),
        ),
        migrations.AddField(
            model_name='casting',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Series'),
        ),
        migrations.AddField(
            model_name='actores',
            name='peliculas',
            field=models.ManyToManyField(null=True, through='api.Casting', to='api.Pelicula'),
        ),
        migrations.AddField(
            model_name='actores',
            name='series',
            field=models.ManyToManyField(null=True, through='api.Casting', to='api.Series'),
        ),
    ]
