# Generated by Django 3.0.9 on 2020-08-14 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('estreno', models.IntegerField(default=2000)),
                ('imagen', models.URLField(help_text='De imdb mismo')),
                ('resumen', models.TextField(help_text='Descripción corta')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('estreno', models.IntegerField(default=2000)),
                ('temporadas', models.IntegerField(default=1)),
                ('episodios', models.IntegerField(default=1)),
                ('imagen', models.URLField(help_text='De imdb mismo')),
                ('resumen', models.TextField(help_text='Descripción corta')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Actores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=150)),
                ('imagen', models.URLField(default='https://m.media-amazon.com/images/G/01/imdb/images/nopicture/medium/name-2135195744._CB466677935_.png', help_text='De imdb mismo')),
                ('peliculas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Pelicula')),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Series')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
