# Generated by Django 3.0.9 on 2020-08-18 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200817_2026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reparto',
            new_name='PeliculasReparto',
        ),
        migrations.CreateModel(
            name='SeriesReparto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=150)),
                ('imagen', models.URLField(default='https://m.media-amazon.com/images/G/01/imdb/images/nopicture/medium/name-2135195744._CB466677935_.png', help_text='De imdb mismo')),
                ('nacimiento', models.DateField()),
                ('actores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Actores')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Series')),
            ],
        ),
        migrations.AddField(
            model_name='series',
            name='equipo',
            field=models.ManyToManyField(through='api.SeriesReparto', to='api.Actores'),
        ),
    ]
